### ISSUE TITLE
AB#12971 Installation failure for some users when installing from local copy of repo

### ISSUE THREAD

**Issue by camagallen** [KenSciResearch/fairMLHealth#25]
On some machines installation will fail when installing from a local copy of the repo. The current suggsted workaround is as follows:

1. Download the repo from github
2. Open setup.py and replace all “fairMLHealth” with “fairmlhealth”
3. Install with “pip install <path to the downloaded folder>
4. import with “import fairmlhealth”

**Comment by madelinezent** [comment]
Thank you for posting this fix!
